"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-14 17:39:41.371348
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_drift_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('line', sa.String(length=120), nullable=True),
    sa.Column('predicted_month', sa.String(length=10), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=True),
    sa.Column('actual_demand', sa.Float(), nullable=False),
    sa.Column('absolute_error', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_drift_records_model_version'), 'ml_drift_records', ['model_version'], unique=False)
    op.create_table('ml_model_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('model_metadata', sa.JSON(), nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_model_artifacts_model_name'), 'ml_model_artifacts', ['model_name'], unique=False)
    op.create_index(op.f('ix_ml_model_artifacts_version'), 'ml_model_artifacts', ['version'], unique=True)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('line', sa.String(length=120), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('with_history', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_model_version'), 'ml_predictions', ['model_version'], unique=False)
    op.create_table('ml_training_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('event_month', sa.Date(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('line', sa.String(length=120), nullable=False),
    sa.Column('sales_count', sa.Float(), nullable=False),
    sa.Column('purchases_count', sa.Float(), nullable=False),
    sa.Column('avg_margin', sa.Float(), nullable=False),
    sa.Column('avg_sale_price', sa.Float(), nullable=False),
    sa.Column('avg_purchase_price', sa.Float(), nullable=False),
    sa.Column('avg_days_inventory', sa.Float(), nullable=False),
    sa.Column('inventory_rotation', sa.Float(), nullable=False),
    sa.Column('lag_1', sa.Float(), nullable=False),
    sa.Column('lag_3', sa.Float(), nullable=False),
    sa.Column('lag_6', sa.Float(), nullable=False),
    sa.Column('rolling_mean_3', sa.Float(), nullable=False),
    sa.Column('rolling_mean_6', sa.Float(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month_sin', sa.Float(), nullable=False),
    sa.Column('month_cos', sa.Float(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('quarter_sin', sa.Float(), nullable=True),
    sa.Column('quarter_cos', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version', 'vehicle_type', 'brand', 'model', 'line', 'event_month', name='uq_ml_training_feature')
    )
    op.create_index(op.f('ix_ml_training_features_brand'), 'ml_training_features', ['brand'], unique=False)
    op.create_index(op.f('ix_ml_training_features_event_month'), 'ml_training_features', ['event_month'], unique=False)
    op.create_index(op.f('ix_ml_training_features_line'), 'ml_training_features', ['line'], unique=False)
    op.create_index(op.f('ix_ml_training_features_model'), 'ml_training_features', ['model'], unique=False)
    op.create_index(op.f('ix_ml_training_features_model_version'), 'ml_training_features', ['model_version'], unique=False)
    op.create_index(op.f('ix_ml_training_features_vehicle_type'), 'ml_training_features', ['vehicle_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_training_features_vehicle_type'), table_name='ml_training_features')
    op.drop_index(op.f('ix_ml_training_features_model_version'), table_name='ml_training_features')
    op.drop_index(op.f('ix_ml_training_features_model'), table_name='ml_training_features')
    op.drop_index(op.f('ix_ml_training_features_line'), table_name='ml_training_features')
    op.drop_index(op.f('ix_ml_training_features_event_month'), table_name='ml_training_features')
    op.drop_index(op.f('ix_ml_training_features_brand'), table_name='ml_training_features')
    op.drop_table('ml_training_features')
    op.drop_index(op.f('ix_ml_predictions_model_version'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_ml_model_artifacts_version'), table_name='ml_model_artifacts')
    op.drop_index(op.f('ix_ml_model_artifacts_model_name'), table_name='ml_model_artifacts')
    op.drop_table('ml_model_artifacts')
    op.drop_index(op.f('ix_ml_drift_records_model_version'), table_name='ml_drift_records')
    op.drop_table('ml_drift_records')
    # ### end Alembic commands ###
